#!/bin/bash
#!/bin/bash



# find all files with a .gif extension in the current directory and all sub-directories

files=$(find . -type f -name "*.gif")



# loop through the list of files

for file in $files; do

	  # remove the .gif extension from the file name

	    file_name=$(echo "$file" | sed 's/\.[^.]*$//')



	      # add the file name to an array

	        file_names+=($file_name)

	done



	# sort the array of file names case-insensitively

	sorted_file_names=$(echo "${file_names[@]}" | tr '[:upper:]' '[:lower:]' | sort)



	# display the sorted list of file names

	printf '%s\n' $sorted_file_names


